all: badDataPar bruteForce

badDataPar: badDataPar.c
	gcc -Wall -Werror -pedantic-errors badDataPar.c  -o badDataPar

bruteForce: bruteForce.c
	gcc -Wall -Werror -pedantic-errors bruteForce.c -o bruteForce
