all: otherDiningOut DPP diningOut

otherDiningOut: otherDiningOut.c
	gcc -Wall -Werror -pedantic-errors -pthread otherDiningOut.c  -o otherDiningOut

DPP: DPP.c
	gcc -Wall -Werror -pthread DPP.c -o DPP

diningOut: diningOut.c
	gcc -Wall -Werror -pedantic-errors -pthread diningOut.c  -o diningOut
