all: otherDiningOut DPP diningOut

otherDiningOut: otherDiningOut.c
	gcc -Wall -Werror -pedantic-errors -pthread otherDiningOut.c  -o otherDiningOut


diningOut: diningOut.c
	gcc -Wall -Werror -pedantic-errors -pthread diningOut.c  -o diningOut
